-- ============================================================
-- AI Financial Fraud Investigation Agent - Setup Script
-- ============================================================
-- Run this script in a Snowflake worksheet with ACCOUNTADMIN role
-- to create the complete fraud investigation environment.
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- 1. Database and Schemas
CREATE OR REPLACE DATABASE FRAUD_INVESTIGATION_DB COMMENT = 'AI Financial Fraud Investigation Agent Project';
USE DATABASE FRAUD_INVESTIGATION_DB;
CREATE SCHEMA IF NOT EXISTS RAW COMMENT = 'Raw synthetic data';
CREATE SCHEMA IF NOT EXISTS ANALYTICS COMMENT = 'Derived analytics and investigation data';
CREATE SCHEMA IF NOT EXISTS AI COMMENT = 'AI models, agents, and semantic layers';

-- 2. Core Tables
CREATE OR REPLACE TABLE RAW.CUSTOMERS (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50), EMAIL VARCHAR(100), PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE, SSN_LAST4 VARCHAR(4), ADDRESS_LINE1 VARCHAR(200),
    CITY VARCHAR(100), STATE VARCHAR(2), ZIP_CODE VARCHAR(10), COUNTRY VARCHAR(3) DEFAULT 'USA',
    ACCOUNT_OPEN_DATE DATE, ACCOUNT_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    RISK_SCORE NUMBER(5,2) DEFAULT 0, RISK_TIER VARCHAR(10) DEFAULT 'LOW',
    ANNUAL_INCOME NUMBER(12,2), CREDIT_SCORE NUMBER(3),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MERCHANTS (
    MERCHANT_ID VARCHAR(20) PRIMARY KEY,
    MERCHANT_NAME VARCHAR(200), CATEGORY VARCHAR(50), MCC_CODE VARCHAR(4),
    ADDRESS VARCHAR(300), CITY VARCHAR(100), STATE VARCHAR(2), ZIP_CODE VARCHAR(10),
    COUNTRY VARCHAR(3) DEFAULT 'USA', LATITUDE NUMBER(10,7), LONGITUDE NUMBER(10,7),
    RISK_LEVEL VARCHAR(10) DEFAULT 'LOW', IS_ONLINE BOOLEAN DEFAULT FALSE,
    REGISTERED_DATE DATE, CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.DEVICES (
    DEVICE_ID VARCHAR(20) PRIMARY KEY, CUSTOMER_ID VARCHAR(20),
    DEVICE_TYPE VARCHAR(30), DEVICE_MODEL VARCHAR(100), OS_TYPE VARCHAR(30), OS_VERSION VARCHAR(20),
    BROWSER VARCHAR(50), IP_ADDRESS VARCHAR(45), DEVICE_FINGERPRINT VARCHAR(64),
    FIRST_SEEN_AT TIMESTAMP_NTZ, LAST_SEEN_AT TIMESTAMP_NTZ, IS_TRUSTED BOOLEAN DEFAULT FALSE,
    LOCATION_CITY VARCHAR(100), LOCATION_STATE VARCHAR(2), LOCATION_COUNTRY VARCHAR(3) DEFAULT 'USA',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.TRANSACTIONS (
    TRANSACTION_ID VARCHAR(20) PRIMARY KEY, CUSTOMER_ID VARCHAR(20), MERCHANT_ID VARCHAR(20), DEVICE_ID VARCHAR(20),
    TRANSACTION_DATE TIMESTAMP_NTZ, AMOUNT NUMBER(12,2), CURRENCY VARCHAR(3) DEFAULT 'USD',
    TRANSACTION_TYPE VARCHAR(20), CHANNEL VARCHAR(20), STATUS VARCHAR(20) DEFAULT 'COMPLETED',
    IS_INTERNATIONAL BOOLEAN DEFAULT FALSE, IS_CARD_PRESENT BOOLEAN DEFAULT TRUE,
    RESPONSE_CODE VARCHAR(10), AUTH_CODE VARCHAR(20), IP_ADDRESS VARCHAR(45),
    LATITUDE NUMBER(10,7), LONGITUDE NUMBER(10,7),
    IS_FRAUD BOOLEAN DEFAULT FALSE, FRAUD_TYPE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ANALYTICS.FRAUD_CASES (
    CASE_ID VARCHAR(20) PRIMARY KEY, CUSTOMER_ID VARCHAR(20), TRANSACTION_ID VARCHAR(20), ALERT_ID VARCHAR(20),
    CASE_STATUS VARCHAR(20) DEFAULT 'OPEN', PRIORITY VARCHAR(10) DEFAULT 'MEDIUM',
    ASSIGNED_TO VARCHAR(100), FRAUD_TYPE VARCHAR(50),
    ESTIMATED_LOSS NUMBER(12,2), ACTUAL_LOSS NUMBER(12,2),
    RISK_SCORE NUMBER(5,2), AI_CONFIDENCE_SCORE NUMBER(5,4), AI_RECOMMENDATION VARCHAR(500),
    OPENED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), CLOSED_AT TIMESTAMP_NTZ, RESOLUTION VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ANALYTICS.ALERTS (
    ALERT_ID VARCHAR(20) PRIMARY KEY, TRANSACTION_ID VARCHAR(20), CUSTOMER_ID VARCHAR(20),
    ALERT_TYPE VARCHAR(50), SEVERITY VARCHAR(10), RULE_NAME VARCHAR(100), RULE_DESCRIPTION TEXT,
    SCORE NUMBER(5,2), STATUS VARCHAR(20) DEFAULT 'NEW',
    REVIEWED_BY VARCHAR(100), REVIEWED_AT TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ANALYTICS.INVESTIGATION_NOTES (
    NOTE_ID VARCHAR(20) PRIMARY KEY, CASE_ID VARCHAR(20), NOTE_TYPE VARCHAR(30), AUTHOR VARCHAR(100),
    CONTENT TEXT, AI_GENERATED BOOLEAN DEFAULT FALSE, SENTIMENT_SCORE NUMBER(5,4), KEY_ENTITIES VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- 3. AI Functions (requires Cortex AI)
CREATE OR REPLACE FUNCTION AI.ANALYZE_TRANSACTION_PATTERN(P_CUSTOMER_ID VARCHAR)
RETURNS VARCHAR AS
$$
SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.3-70b',
    'You are a financial fraud analyst AI. Analyze this customer transaction summary and provide:
1. Risk assessment (LOW/MEDIUM/HIGH/CRITICAL) 2. Key suspicious patterns 3. Recommended actions 4. Confidence level
Transaction data: ' || (
        SELECT OBJECT_CONSTRUCT(
            'customer_id', P_CUSTOMER_ID, 'total_transactions', COUNT(*), 'total_amount', SUM(AMOUNT),
            'avg_amount', ROUND(AVG(AMOUNT), 2), 'max_amount', MAX(AMOUNT),
            'fraud_count', SUM(CASE WHEN IS_FRAUD THEN 1 ELSE 0 END),
            'channels', ARRAY_AGG(DISTINCT CHANNEL), 'fraud_types', ARRAY_AGG(DISTINCT FRAUD_TYPE),
            'international_pct', ROUND(SUM(CASE WHEN IS_INTERNATIONAL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(*), 0), 1)
        )::VARCHAR FROM FRAUD_INVESTIGATION_DB.RAW.TRANSACTIONS WHERE CUSTOMER_ID = P_CUSTOMER_ID))
$$;

CREATE OR REPLACE FUNCTION AI.GENERATE_CASE_SUMMARY(P_CASE_ID VARCHAR)
RETURNS VARCHAR AS
$$
SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.3-70b',
    'Generate a concise executive summary of this fraud case including: status, key findings, risk level, financial impact, and next steps.
Case data: ' || (
        SELECT OBJECT_CONSTRUCT(
            'case_id', fc.CASE_ID, 'status', fc.CASE_STATUS, 'priority', fc.PRIORITY,
            'fraud_type', fc.FRAUD_TYPE, 'estimated_loss', fc.ESTIMATED_LOSS, 'risk_score', fc.RISK_SCORE,
            'ai_confidence', fc.AI_CONFIDENCE_SCORE, 'assigned_to', fc.ASSIGNED_TO, 'customer_id', fc.CUSTOMER_ID,
            'notes', (SELECT ARRAY_AGG(OBJECT_CONSTRUCT('type', NOTE_TYPE, 'content', LEFT(CONTENT, 200), 'author', AUTHOR))
                       FROM FRAUD_INVESTIGATION_DB.ANALYTICS.INVESTIGATION_NOTES n WHERE n.CASE_ID = fc.CASE_ID)
        )::VARCHAR FROM FRAUD_INVESTIGATION_DB.ANALYTICS.FRAUD_CASES fc WHERE fc.CASE_ID = P_CASE_ID))
$$;

CREATE OR REPLACE FUNCTION AI.CLASSIFY_TRANSACTION_RISK(P_TRANSACTION_ID VARCHAR)
RETURNS VARCHAR AS
$$
SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.3-70b',
    'Classify the fraud risk as exactly one of: LOW_RISK, MEDIUM_RISK, HIGH_RISK, CRITICAL_RISK. Then provide a one-sentence justification. Format: RISK_LEVEL: justification
Transaction: ' || (
        SELECT OBJECT_CONSTRUCT(
            'transaction_id', t.TRANSACTION_ID, 'amount', t.AMOUNT, 'type', t.TRANSACTION_TYPE,
            'channel', t.CHANNEL, 'is_international', t.IS_INTERNATIONAL, 'is_card_present', t.IS_CARD_PRESENT,
            'hour_of_day', HOUR(t.TRANSACTION_DATE), 'customer_risk_tier', c.RISK_TIER,
            'merchant_category', m.CATEGORY, 'merchant_risk', m.RISK_LEVEL
        )::VARCHAR FROM FRAUD_INVESTIGATION_DB.RAW.TRANSACTIONS t
        LEFT JOIN FRAUD_INVESTIGATION_DB.RAW.CUSTOMERS c ON t.CUSTOMER_ID = c.CUSTOMER_ID
        LEFT JOIN FRAUD_INVESTIGATION_DB.RAW.MERCHANTS m ON t.MERCHANT_ID = m.MERCHANT_ID
        WHERE t.TRANSACTION_ID = P_TRANSACTION_ID))
$$;

CREATE OR REPLACE FUNCTION AI.RECOMMEND_ESCALATION(P_CASE_ID VARCHAR)
RETURNS VARCHAR AS
$$
SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.3-70b',
    'Determine: 1. Should this case be escalated? (YES/NO) 2. Priority (P1-IMMEDIATE, P2-URGENT, P3-STANDARD) 3. Target (Senior Analyst, Fraud Manager, Legal, Law Enforcement) 4. Key reasons 5. Timeline
Case data: ' || (
        SELECT OBJECT_CONSTRUCT(
            'case_id', fc.CASE_ID, 'status', fc.CASE_STATUS, 'current_priority', fc.PRIORITY,
            'fraud_type', fc.FRAUD_TYPE, 'estimated_loss', fc.ESTIMATED_LOSS, 'risk_score', fc.RISK_SCORE,
            'days_open', DATEDIFF('day', fc.OPENED_AT, CURRENT_TIMESTAMP()),
            'note_count', (SELECT COUNT(*) FROM FRAUD_INVESTIGATION_DB.ANALYTICS.INVESTIGATION_NOTES n WHERE n.CASE_ID = fc.CASE_ID),
            'customer_risk_tier', (SELECT RISK_TIER FROM FRAUD_INVESTIGATION_DB.RAW.CUSTOMERS c WHERE c.CUSTOMER_ID = fc.CUSTOMER_ID),
            'related_alerts', (SELECT COUNT(*) FROM FRAUD_INVESTIGATION_DB.ANALYTICS.ALERTS a WHERE a.CUSTOMER_ID = fc.CUSTOMER_ID)
        )::VARCHAR FROM FRAUD_INVESTIGATION_DB.ANALYTICS.FRAUD_CASES fc WHERE fc.CASE_ID = P_CASE_ID))
$$;

SELECT 'Setup complete! Tables and AI functions created in FRAUD_INVESTIGATION_DB.' AS STATUS;
